// angle-dashboard/angular2/ng2angle/src/app/routes/dashboard/dashboardv2/dashboardv2.component.ts
import { Component, OnInit } from '@angular/core';
import { Http } from '@angular/http';

import { ColorsService } from '../../../shared/colors/colors.service';

@Component({
    selector: 'app-dashboardv2',
    templateUrl: './dashboardv2.component.html',
    styleUrls: ['./dashboardv2.component.scss']
})
export class Dashboardv2Component implements OnInit {

    sparkOptions1 = {
        barColor: this.colors.byName('info'),
        height: 60,
        barWidth: 10,
        barSpacing: 6,
        chartRangeMin: 0
    };

    sparkOptions2 = {
        type: 'line',
        height: 60,
        width: '80%',
        lineWidth: 2,
        lineColor: this.colors.byName('purple'),
        chartRangeMin: 0,
        spotColor: '#888',
        minSpotColor: this.colors.byName('purple'),
        maxSpotColor: this.colors.byName('purple'),
        fillColor: '',
        highlightLineColor: '#fff',
        spotRadius: 3,
        resize: true
    };

    barStackedData: any;
    barStackedOptions = {
        series: {
            stack: true,
            bars: {
                align: 'center',
                lineWidth: 0,
                show: true,
                barWidth: 0.6,
                fill: 0.9
            }
        },
        grid: {
            borderColor: '#eee',
            borderWidth: 1,
            hoverable: true,
            backgroundColor: '#fcfcfc'
        },
        tooltip: true,
        tooltipOpts: {
            content: (label, x, y) => { return x + ' : ' + y; }
        },
        xaxis: {
            tickColor: '#fcfcfc',
            mode: 'categories'
        },
        yaxis: {
            min: 0,
            max: 200, // optional: use it for a clear represetation
            // position: ($rootScope.app.layout.isRTL ? 'right' : 'left'),
            tickColor: '#eee'
        },
        shadowSize: 0
    };

    splineData: any;
    splineOptions = {
        series: {
            lines: {
                show: false
            },
            points: {
                show: true,
                radius: 4
            },
            splines: {
                show: true,
                tension: 0.4,
                lineWidth: 1,
                fill: 0.5
            }
        },
        grid: {
            borderColor: '#eee',
            borderWidth: 1,
            hoverable: true,
            backgroundColor: '#fcfcfc'
        },
        tooltip: true,
        tooltipOpts: {
            content: (label, x, y) => { return x + ' : ' + y; }
        },
        xaxis: {
            tickColor: '#fcfcfc',
            mode: 'categories'
        },
        yaxis: {
            min: 0,
            max: 150, // optional: use it for a clear represetation
            tickColor: '#eee',
            // position: ($rootScope.app.layout.isRTL ? 'right' : 'left'),
            tickFormatter: (v) => {
                return v/* + ' visitors'*/;
            }
        },
        shadowSize: 0
    };


    easyPiePercent1 = 60;
    easyPiePercent2 = 30;
    easyPiePercent3 = 50;
    easyPiePercent4 = 75;

    pieOptions1 = {
        animate: {
            duration: 800,
            enabled: true
        },
        barColor: this.colors.byName('info'),
        trackColor: '#edf2f6',
        scaleColor: false,
        lineWidth: 2,
        lineCap: 'round',
        size: 130
    };
    pieOptions2 = {
        animate: {
            duration: 800,
            enabled: true
        },
        barColor: this.colors.byName('pink'),
        trackColor: '#edf2f6',
        scaleColor: false,
        lineWidth: 2,
        lineCap: 'round',
        size: 130
    };
    pieOptions3 = {
        animate: {
            duration: 800,
            enabled: true
        },
        barColor: this.colors.byName('purple'),
        trackColor: '#edf2f6',
        scaleColor: false,
        lineWidth: 2,
        lineCap: 'round',
        size: 130
    };
    pieOptions4 = {
        animate: {
            duration: 800,
            enabled: true
        },
        barColor: this.colors.byName('warning'),
        trackColor: '#edf2f6',
        scaleColor: false,
        lineWidth: 2,
        lineCap: 'round',
        size: 130
    };


    constructor(private colors: ColorsService, private http: Http) {
        http.get('assets/server/chart/barstackedv2.json').map(data => data.json()).subscribe(data => this.barStackedData = data);
        http.get('assets/server/chart/splinev2.json').map(data => data.json()).subscribe(data => this.splineData = data);
    }

    ngOnInit() {
    }

}

<div class="content-heading">
    Dashboard
    <small>{{ 'dashboard.WELCOME' | translate }} !</small>
</div>
<div class="row">
    <div class="col-lg-4">
        <!-- START List group-->
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row row-table pv-lg">
                    <div class="col-xs-6">
                        <p class="m0 lead">1204</p>
                        <p class="m0">
                            <small>Commits this month</small>
                        </p>
                    </div>
                    <div class="col-xs-6 text-center">
                        <div [sparkline]="sparkOptions1" values="3,6,7,8,4,5"></div>
                    </div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row row-table pv-lg">
                    <div class="col-xs-6">
                        <p class="m0 lead">$ 3,200.00</p>
                        <p class="m0">
                            <small>Available budget</small>
                        </p>
                    </div>
                    <div class="col-xs-6 text-center">
                        <div [sparkline]="sparkOptions2" values="7,3,4,7,5,9,4,4,7,5,9,6,4"></div>
                    </div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="row row-table pv-lg">
                    <div class="col-xs-6">
                        <p class="m0 lead">67</p>
                        <p class="m0">
                            <small>New followers</small>
                        </p>
                    </div>
                    <div class="col-xs-6">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#" tooltip="Katie">
                                    <img class="img-responsive img-circle thumb24" src="assets/img/user/02.jpg" alt="Follower" />
                                </a>
                            </li>
                            <li>
                                <a href="#" tooltip="Cody">
                                    <img class="img-responsive img-circle thumb24" src="assets/img/user/01.jpg" alt="Follower" />
                                </a>
                            </li>
                            <li>
                                <a href="#" tooltip="Tamara">
                                    <img class="img-responsive img-circle thumb24" src="assets/img/user/03.jpg" alt="Follower" />
                                </a>
                            </li>
                            <li>
                                <a href="#" tooltip="Gene">
                                    <img class="img-responsive img-circle thumb24" src="assets/img/user/04.jpg" alt="Follower" />
                                </a>
                            </li>
                            <li>
                                <a href="#" tooltip="Marsha">
                                    <img class="img-responsive img-circle thumb24" src="assets/img/user/04.jpg" alt="Follower" />
                                </a>
                            </li>
                            <li>
                                <a href="#" tooltip="Robin">
                                    <img class="img-responsive img-circle thumb24" src="assets/img/user/09.jpg" alt="Follower" />
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
        <!-- END List group-->
    </div>
    <div class="col-lg-8">
        <!-- START bar chart-->
        <div class="panel" id="panelChart3">
            <div class="panel-heading">
                <!-- START button group-->
                <div class="pull-right btn-group" dropdown>
                    <button class="btn btn-default btn-sm" type="button" dropdownToggle>Monthly</button>
                    <ul dropdownMenu class="dropdown-menu fadeInLeft animated" role="menu">
                        <li><a href="#">Daily</a></li>
                        <li><a href="#">Monthly</a></li>
                        <li><a href="#">Yearly</a></li>
                    </ul>
                </div>
                <!-- END button group-->
                <div class="panel-title">Projects Hours</div>
            </div>
            <div class="panel-body">
                <div flot [dataset]="barStackedData" [options]="barStackedOptions" height="250"></div>
            </div>
        </div>
        <!-- END bar chart-->
    </div>
</div>
<div class="unwrap mv-lg">
    <!-- START chart-->
    <div class="panel" id="panelChart9">
        <div class="panel-heading">
            <!-- START button group-->
            <div class="pull-right btn-group" dropdown>
                <button class="btn btn-default btn-sm" type="button" dropdownToggle>All time</button>
                <ul dropdownMenu class="dropdown-menu fadeInLeft animated" role="menu">
                    <li><a href="#">Daily</a></li>
                    <li><a href="#">Monthly</a></li>
                    <li class="divider"></li>
                    <li><a href="#">All time</a></li>
                </ul>
            </div>
            <!-- END button group-->
            <div class="panel-title">Overall progress</div>
        </div>
        <div class="panel-body">
            <div flot [dataset]="splineData" [options]="splineOptions" height="300"></div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-3 col-xs-6 text-center">
                    <p>Projects</p>
                    <div class="h1">25</div>
                </div>
                <div class="col-sm-3 col-xs-6 text-center">
                    <p>Teammates</p>
                    <div class="h1">85</div>
                </div>
                <div class="col-sm-3 col-xs-6 text-center">
                    <p>Hours</p>
                    <div class="h1">380</div>
                </div>
                <div class="col-sm-3 col-xs-6 text-center">
                    <p>Budget</p>
                    <div class="h1">$ 10,000.00</div>
                </div>
            </div>
        </div>
    </div>
    <!-- END chart-->
</div>
<!-- START radial charts-->
<div class="row mb-lg">
    <div class="col-sm-3 col-xs-6 text-center">
        <p>Current Project</p>
        <div class="text-center pv-lg">
            <div class="easypie-chart easypie-chart-md" easypiechart [options]="pieOptions1" [percent]="easyPiePercent1">
                <span>{{easyPiePercent1}}%</span>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-xs-6 text-center">
        <p>Current Progress</p>
        <div class="text-center pv-lg">
            <div class="easypie-chart easypie-chart-md" easypiechart [options]="pieOptions2" [percent]="easyPiePercent2">
                <span>{{easyPiePercent2}}%</span>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-xs-6 text-center">
        <p>Space Usage</p>
        <div class="text-center pv-lg">
            <div class="easypie-chart easypie-chart-md" easypiechart [options]="pieOptions3" [percent]="easyPiePercent3">
                <span>{{easyPiePercent3}}%</span>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-xs-6 text-center">
        <p>Interactions</p>
        <div class="text-center pv-lg">
            <div class="easypie-chart easypie-chart-md" easypiechart [options]="pieOptions4" [percent]="easyPiePercent4">
                <span>{{easyPiePercent4}}%</span>
            </div>
        </div>
    </div>
</div>
<!-- START radial charts-->
<!-- START Multiple List group-->
<div class="list-group">
    <a class="list-group-item" href="#">
        <table class="wd-wide">
            <tbody>
                <tr>
                    <td class="wd-xs">
                        <div class="ph">
                            <img class="media-box-object img-responsive img-rounded thumb64" src="assets/img/dummy.png" alt="" />
                        </div>
                    </td>
                    <td>
                        <div class="ph">
                            <h4 class="media-box-heading">Project A</h4>
                            <small class="text-muted">Vestibulum ante ipsum primis in faucibus orci</small>
                        </div>
                    </td>
                    <td class="wd-sm hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0">Last change</p>
                            <small class="text-muted">4 weeks ago</small>
                        </div>
                    </td>
                    <td class="wd-xs hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0 text-muted">
                                <em class="icon-user mr fa-lg"></em>26</p>
                        </div>
                    </td>
                    <td class="wd-xs hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0 text-muted">
                                <em class="icon-doc mr fa-lg"></em>3500</p>
                        </div>
                    </td>
                    <td class="wd-sm">
                        <div class="ph">
                            <progressbar class="m0 progress-xs" value="80" type="success">80%</progressbar>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </a>
</div>
<div class="list-group">
    <a class="list-group-item" href="#">
        <table class="wd-wide">
            <tbody>
                <tr>
                    <td class="wd-xs">
                        <div class="ph">
                            <img class="media-box-object img-responsive img-rounded thumb64" src="assets/img/dummy.png" alt="" />
                        </div>
                    </td>
                    <td>
                        <div class="ph">
                            <h4 class="media-box-heading">Project X</h4>
                            <small class="text-muted">Vestibulum ante ipsum primis in faucibus orci</small>
                        </div>
                    </td>
                    <td class="wd-sm hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0">Last change</p>
                            <small class="text-muted">Today at 06:23 am</small>
                        </div>
                    </td>
                    <td class="wd-xs hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0 text-muted">
                                <em class="icon-user mr fa-lg"></em>3</p>
                        </div>
                    </td>
                    <td class="wd-xs hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0 text-muted">
                                <em class="icon-doc mr fa-lg"></em>150</p>
                        </div>
                    </td>
                    <td class="wd-sm">
                        <div class="ph">
                            <progressbar class="m0 progress-xs" value="50" type="purple">50%</progressbar>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </a>
</div>
<div class="list-group">
    <a class="list-group-item" href="#">
        <table class="wd-wide">
            <tbody>
                <tr>
                    <td class="wd-xs">
                        <div class="ph">
                            <img class="media-box-object img-responsive img-rounded thumb64" src="assets/img/dummy.png" alt="" />
                        </div>
                    </td>
                    <td>
                        <div class="ph">
                            <h4 class="media-box-heading">Project Z</h4>
                            <small class="text-muted">Vestibulum ante ipsum primis in faucibus orci</small>
                        </div>
                    </td>
                    <td class="wd-sm hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0">Last change</p>
                            <small class="text-muted">Yesterday at 10:20 pm</small>
                        </div>
                    </td>
                    <td class="wd-xs hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0 text-muted">
                                <em class="icon-user mr fa-lg"></em>15</p>
                        </div>
                    </td>
                    <td class="wd-xs hidden-xs hidden-sm">
                        <div class="ph">
                            <p class="m0 text-muted">
                                <em class="icon-doc mr fa-lg"></em>480</p>
                        </div>
                    </td>
                    <td class="wd-sm">
                        <div class="ph">
                            <progressbar class="m0 progress-xs" value="20" type="green">20%</progressbar>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </a>
    <!-- END dashboard main content-->
</div>
<!-- END Multiple List group-->

// angle-dashboard/reactjs/app/components/Dashboard/DashboardV2.jsx
import React from 'react';
import ReactDom from 'react-dom';
import ContentWrapper from '../Layout/ContentWrapper';
import { Grid, Row, Col, Dropdown, MenuItem, Tooltip, OverlayTrigger } from 'react-bootstrap';
import DashboardRun from './DashboardV2.run';

class DashboardV2 extends React.Component {

    componentDidMount() {
        DashboardRun(
            ReactDom.findDOMNode(this.refs.chartBar),
            ReactDom.findDOMNode(this.refs.chartSpline)
            );
    }

    componentWillUnmount() {
        $(this.refs.chartBar).data('plot').shutdown();
        $(this.refs.chartSpline).data('plot').shutdown();
    }

    render() {

        const tooltip = function(text) {
            return (
                <Tooltip id="tooltip">{text}</Tooltip>
            );
        };

        return (
            <ContentWrapper>
                <div className="content-heading">
                    { /* START Language list */ }
                    <div className="pull-right">
                        <Dropdown id="dropdown-tr" pullRight>
                            <Dropdown.Toggle>
                                English
                            </Dropdown.Toggle>
                            <Dropdown.Menu className="animated fadeInUpShort">
                                <MenuItem eventKey="1" data-set-lang="en">English</MenuItem>
                                <MenuItem eventKey="2" data-set-lang="es">Spanish</MenuItem>
                            </Dropdown.Menu>
                        </Dropdown>
                    </div>
                    { /* END Language list */ } Dashboard
                    <small data-localize="dashboard.WELCOME">Welcome to Angle!</small>
                </div>
                <Row>
                    <Col lg={ 4 }>
                        { /* START List group */ }
                        <ul className="list-group">
                            <li className="list-group-item">
                                <Row className="row-table pv-lg">
                                    <Col xs={ 6 }>
                                        <p className="m0 lead">1204</p>
                                        <p className="m0">
                                            <small>Commits this month</small>
                                        </p>
                                    </Col>
                                    <Col xs={ 6 } className="text-center">
                                        <div data-sparkline="" data-bar-color="#23b7e5" data-height="60" data-bar-width="10" data-bar-spacing="6" data-chart-range-min="0" data-values="3,6,7,8,4,5"></div>
                                    </Col>
                                </Row>
                            </li>
                            <li className="list-group-item">
                                <Row className="row-table pv-lg">
                                    <Col xs={ 6 }>
                                        <p className="m0 lead">$ 3,200.00</p>
                                        <p className="m0">
                                            <small>Available budget</small>
                                        </p>
                                    </Col>
                                    <Col xs={ 6 } className="text-center">
                                        <div data-sparkline="" data-type="line" data-height="60" data-width="80%" data-line-width="2" data-line-color="#7266ba" data-chart-range-min="0" data-spot-color="#888"
                                        data-min-spot-color="#7266ba" data-max-spot-color="#7266ba" data-fill-color="" data-highlight-line-color="#fff" data-spot-radius="3"
                                        data-values="7,3,4,7,5,9,4,4,7,5,9,6,4" data-resize="true"></div>
                                    </Col>
                                </Row>
                            </li>
                            <li className="list-group-item">
                                <Row className="row-table pv-lg">
                                    <Col xs={ 6 }>
                                        <p className="m0 lead">67</p>
                                        <p className="m0">
                                            <small>New followers</small>
                                        </p>
                                    </Col>
                                    <Col xs={ 6 }>
                                        <ul className="list-inline text-center">
                                            <li>
                                                <OverlayTrigger placement="top" overlay={tooltip('Katie')}>
                                                    <img src="img/user/02.jpg" alt="Follower" className="img-responsive img-circle thumb24" />
                                                </OverlayTrigger>
                                            </li>
                                            <li>
                                                <OverlayTrigger placement="top" overlay={tooltip("Cody")}>
                                                    <img src="img/user/01.jpg" alt="Follower" className="img-responsive img-circle thumb24" />
                                                </OverlayTrigger>
                                            </li>
                                            <li>
                                                <OverlayTrigger placement="top" overlay={tooltip("Tamara")}>
                                                    <img src="img/user/03.jpg" alt="Follower" className="img-responsive img-circle thumb24" />
                                                </OverlayTrigger>
                                            </li>
                                            <li>
                                                <OverlayTrigger placement="top" overlay={tooltip("Gene")}>
                                                    <img src="img/user/04.jpg" alt="Follower" className="img-responsive img-circle thumb24" />
                                                </OverlayTrigger>
                                            </li>
                                            <li>
                                                <OverlayTrigger placement="top" overlay={tooltip("Marsha")}>
                                                    <img src="img/user/04.jpg" alt="Follower" className="img-responsive img-circle thumb24" />
                                                </OverlayTrigger>
                                            </li>
                                            <li>
                                                <OverlayTrigger placement="top" overlay={tooltip("Robin")}>
                                                    <img src="img/user/09.jpg" alt="Follower" className="img-responsive img-circle thumb24" />
                                                </OverlayTrigger>
                                            </li>
                                        </ul>
                                    </Col>
                                </Row>
                            </li>
                        </ul>
                        { /* END List group */ }
                    </Col>
                    <Col lg={ 8 }>
                        { /* START bar chart */ }
                        <div id="panelChart3" className="panel">
                            <div className="panel-heading">
                                { /* START button group */ }
                                <div className="pull-right btn-group">
                                    <button type="button" data-toggle="dropdown" className="dropdown-toggle btn btn-default btn-sm">Monthly</button>
                                    <ul role="menu" className="dropdown-menu fadeInLeft animated">
                                        <li><a href="#">Daily</a>
                                        </li>
                                        <li><a href="#">Monthly</a>
                                        </li>
                                        <li><a href="#">Yearly</a>
                                        </li>
                                    </ul>
                                </div>
                                { /* END button group */ }
                                <div className="panel-title">Projects Hours</div>
                            </div>
                            <div className="panel-wrapper">
                                <div className="panel-body">
                                    <div className="indicator show">
                                        <span className="spinner"></span>
                                    </div>
                                    <div ref="chartBar" className="chart-bar-stackedv2 flot-chart"></div>
                                </div>
                            </div>
                        </div>
                        { /* END bar chart */ }
                    </Col>
                </Row>
                <div className="unwrap mv-lg">
                    { /* START chart */ }
                    <div id="panelChart9" className="panel">
                        <div className="panel-heading">
                            { /* START button group */ }
                            <div className="pull-right btn-group">
                                <button type="button" data-toggle="dropdown" className="dropdown-toggle btn btn-default btn-sm">All time</button>
                                <ul role="menu" className="dropdown-menu fadeInLeft animated">
                                    <li><a href="#">Daily</a>
                                    </li>
                                    <li><a href="#">Monthly</a>
                                    </li>
                                    <li className="divider"></li>
                                    <li><a href="#">All time</a>
                                    </li>
                                </ul>
                            </div>
                            { /* END button group */ }
                            <div className="panel-title">Overall progress</div>
                        </div>
                        <div className="panel-wrapper">
                            <div className="panel-body">
                                <div ref="chartSpline" className="chart-splinev2 flot-chart"></div>
                            </div>
                            <div className="panel-body">
                                <Row>
                                    <Col sm={ 3 } xs={ 6 } className="text-center">
                                        <p>Projects</p>
                                        <div className="h1">25</div>
                                    </Col>
                                    <Col sm={ 3 } xs={ 6 } className="text-center">
                                        <p>Teammates</p>
                                        <div className="h1">85</div>
                                    </Col>
                                    <Col sm={ 3 } xs={ 6 } className="text-center">
                                        <p>Hours</p>
                                        <div className="h1">380</div>
                                    </Col>
                                    <Col sm={ 3 } xs={ 6 } className="text-center">
                                        <p>Budget</p>
                                        <div className="h1">$ 10,000.00</div>
                                    </Col>
                                </Row>
                            </div>
                        </div>
                    </div>
                    { /* END chart */ }
                </div>
                { /* START radial charts */ }
                <Row className="mb-lg">
                    <Col sm={ 3 } xs={ 6 } className="text-center">
                        <p>Current Project</p>
                        <canvas data-classyloader="" data-height="150px" data-diameter="60" data-font-size="25px" data-percentage="60" data-speed="30" data-line-color="#23b7e5" data-remaining-line-color="#edf2f6"
                        data-line-width="2"></canvas>
                    </Col>
                    <Col sm={ 3 } xs={ 6 } className="text-center">
                        <p>Current Progress</p>
                        <canvas data-classyloader="" data-height="150px" data-diameter="60" data-font-size="25px" data-percentage="30" data-speed="30" data-line-color="#f532e5" data-remaining-line-color="#edf2f6"
                        data-line-width="2"></canvas>
                    </Col>
                    <Col sm={ 3 } xs={ 6 } className="text-center">
                        <p>Space Usage</p>
                        <canvas data-classyloader="" data-height="150px" data-diameter="60" data-font-size="25px" data-percentage="50" data-speed="30" data-line-color="#7266ba" data-remaining-line-color="#edf2f6"
                        data-line-width="2"></canvas>
                    </Col>
                    <Col sm={ 3 } xs={ 6 } className="text-center">
                        <p>Interactions</p>
                        <canvas data-classyloader="" data-height="150px" data-diameter="60" data-font-size="25px" data-percentage="75" data-speed="30" data-line-color="#ff902b" data-remaining-line-color="#edf2f6"
                        data-line-width="2"></canvas>
                    </Col>
                </Row>
                { /* START radial charts */ }
                { /* START Multiple List group */ }
                <div className="list-group">
                    <a href="#" className="list-group-item">
                        <table className="wd-wide">
                            <tbody>
                                <tr>
                                    <td className="wd-xs">
                                        <div className="ph">
                                            <img src="img/dummy.png" alt="" className="media-box-object img-responsive img-rounded thumb64" />
                                        </div>
                                    </td>
                                    <td>
                                        <div className="ph">
                                            <h4 className="media-box-heading">Project A</h4>
                                            <small className="text-muted">Vestibulum ante ipsum primis in faucibus orci</small>
                                        </div>
                                    </td>
                                    <td className="wd-sm hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0">Last change</p>
                                            <small className="text-muted">4 weeks ago</small>
                                        </div>
                                    </td>
                                    <td className="wd-xs hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0 text-muted">
                                                <em className="icon-users mr fa-lg"></em>26</p>
                                        </div>
                                    </td>
                                    <td className="wd-xs hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0 text-muted">
                                                <em className="icon-doc mr fa-lg"></em>3500</p>
                                        </div>
                                    </td>
                                    <td className="wd-sm">
                                        <div className="ph">
                                            <progressbar value="80" type="success" className="m0 progress-xs">80%</progressbar>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </a>
                </div>
                <div className="list-group">
                    <a href="#" className="list-group-item">
                        <table className="wd-wide">
                            <tbody>
                                <tr>
                                    <td className="wd-xs">
                                        <div className="ph">
                                            <img src="img/dummy.png" alt="" className="media-box-object img-responsive img-rounded thumb64" />
                                        </div>
                                    </td>
                                    <td>
                                        <div className="ph">
                                            <h4 className="media-box-heading">Project X</h4>
                                            <small className="text-muted">Vestibulum ante ipsum primis in faucibus orci</small>
                                        </div>
                                    </td>
                                    <td className="wd-sm hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0">Last change</p>
                                            <small className="text-muted">Today at 06:23 am</small>
                                        </div>
                                    </td>
                                    <td className="wd-xs hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0 text-muted">
                                                <em className="icon-users mr fa-lg"></em>3</p>
                                        </div>
                                    </td>
                                    <td className="wd-xs hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0 text-muted">
                                                <em className="icon-doc mr fa-lg"></em>150</p>
                                        </div>
                                    </td>
                                    <td className="wd-sm">
                                        <div className="ph">
                                            <progressbar value="50" type="purple" className="m0 progress-xs">50%</progressbar>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </a>
                </div>
                <div className="list-group">
                    <a href="#" className="list-group-item">
                        <table className="wd-wide">
                            <tbody>
                                <tr>
                                    <td className="wd-xs">
                                        <div className="ph">
                                            <img src="img/dummy.png" alt="" className="media-box-object img-responsive img-rounded thumb64" />
                                        </div>
                                    </td>
                                    <td>
                                        <div className="ph">
                                            <h4 className="media-box-heading">Project Z</h4>
                                            <small className="text-muted">Vestibulum ante ipsum primis in faucibus orci</small>
                                        </div>
                                    </td>
                                    <td className="wd-sm hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0">Last change</p>
                                            <small className="text-muted">Yesterday at 10:20 pm</small>
                                        </div>
                                    </td>
                                    <td className="wd-xs hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0 text-muted">
                                                <em className="icon-users mr fa-lg"></em>15</p>
                                        </div>
                                    </td>
                                    <td className="wd-xs hidden-xs hidden-sm">
                                        <div className="ph">
                                            <p className="m0 text-muted">
                                                <em className="icon-doc mr fa-lg"></em>480</p>
                                        </div>
                                    </td>
                                    <td className="wd-sm">
                                        <div className="ph">
                                            <progressbar value="20" type="green" className="m0 progress-xs">20%</progressbar>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </a>
                    { /* END dashboard main content */ }
                </div>
                { /* END Multiple List group */ }
            </ContentWrapper>
            );
    }

}

export default DashboardV2;
